#!/usr/bin/python3
"""
Little command line tool to generate a new password.

Requires `xclip` to be installed.

Usage:
./password  # Generates a password of length 12 and copies it to the clipboard

# or optionally specify a custom length:
./password 15
"""
import sys
import secrets
import string
import subprocess

valid_characters = string.printable[:-5]

if __name__ == '__main__':
    if len(sys.argv) > 1:
        try:
            pw_len = int(sys.argv[1])
        except:
            print(f"Usage: {sys.argv[0]} [LEN=12]")
            sys.exit(1)
    else:
        pw_len = 12

    pw = ''.join([ secrets.choice(valid_characters) for _ in range(pw_len) ]).encode('utf-8')
    p = subprocess.run(['xclip', '-selection', 'clipboard'], input=pw)
    sys.exit(p.returncode)

