#!/usr/bin/python3
import sys
import secrets
import string

valid_characters = string.printable[:-5]

if __name__ == '__main__':
    if len(sys.argv) > 1:
        try:
            pw_len = int(sys.argv[1])
        except:
            print(f"Usage: {sys.argv[0]} [LEN=12]")
            sys.exit(1)
    else:
        pw_len = 12

    print(''.join([ secrets.choice(valid_characters) for _ in range(pw_len) ]))

